### ISSUE TITLE
can in knw why water wheel can't work steam engines olso can't work how to get start with create?

### ISSUE THREAD

**Issue by akasia** [ACrazyD/SkyMachina-Reborn#1]

**Comment by ScottAwesome9** [comment]
not the dev, but could you explain or post screenshots of what you mean? ive tested the water wheel and it works, could you also expand on how to get started on create? as some of create is implemented and the rest is being developed/made by the dev

**Comment by akasia** [comment]
![2024-04-21_19 50 17](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/4874979a-6234-4e20-8d95-08b0de83d8e3)
![2024-04-21_19 50 32](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/09c82f47-e06a-427c-a8a6-15acf096de9d)
don;t know how to kick start that water wheel
![Uploading 2024-04-21_19.50.32.png…]()

is that need to setup like this?
![2024-04-21_19 52 27](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/32bb9562-6dae-4e19-a84e-f5262d257057)

**Comment by akasia** [comment]
water wheel not working than i try switch to steam engines campfire can't kick start steam engines has to use basic burner to kick start than can with new issue that did hv flint/steel to kick start endless loop?

![2024-04-21_19 55 45](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/1e754687-1958-4f4c-b171-2e2e00a2a068)

**Comment by akasia** [comment]
ver SkyMachina 2.04

**Comment by ScottAwesome9** [comment]
not sure why campfires wouldn't be working with steam engine try multiple if you haven't already, testing why the waterwheel is being weird

**Comment by akasia** [comment]
this not skyblock base? wired i start ast skyblock map

**Comment by akasia** [comment]
waterwheel is being weird that 1 source block tell not enought water 3 water source block say that lacking power source
zzz water wheel still need power source?!

**Comment by ScottAwesome9** [comment]
looks like your first image had too much water, your second picture should of been working though, try break + replace water wheel and do the 2nd picture again, if that doesnt work try this one
![image](https://github.com/ACrazyD/SkyMachina-Reborn/assets/97322602/53fcfac7-2640-4a92-8837-a590b036d0ca)

**Comment by akasia** [comment]
hmm  still same 
![2024-04-21_20 08 46](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/ee89f1fa-d3b6-4b59-a7ed-cc250151f45d)
![2024-04-21_20 09 02](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/494ecfd7-a78a-4dce-881b-f2677304b0e7)
![Uploading 2024-04-21_20.09.22.png…]()
![2024-04-21_20 10 00](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/b29ddd9d-9ee5-4d9a-84a0-522d916925da)

**Comment by akasia** [comment]
zz interstry to play this modpack but sadly somany recipe unfinish or can;t be search on rei

**Comment by ScottAwesome9** [comment]
as i mentioned before, create is getting a massive overhaul, you can check the discord for more info, i can help you find recipes though or similar things if you do need that help

**Comment by akasia** [comment]
discord is an issue i can't loging bcouse do't hv sucre code can't find out how to fix it

**Comment by ACrazyD** [comment]
I will mention that not to long ago, i added this mod - https://www.curseforge.com/minecraft/mc-mods/create-picky-waterwheels - It tweaks the way waterwheels and windmills work to be less cheesey.

As for the steam boiler issue, ill add it to my list :)

**Comment by akasia** [comment]
- -!  so i need 5x5 water pool to make 1 small water wheel  it work?
 -

**Comment by ACrazyD** [comment]
Should - if not ill do some testing and get back to you - lookin into the boiler issue atm

**Comment by akasia** [comment]
> Should - if not ill do some testing and get back to you - lookin into the boiler issue atm

need more work on questline for ppl like didt look cafuly on mod list

**Comment by ACrazyD** [comment]
Thats the plan - im just running into a creative block for the quests after doing the greg lines XD

**Comment by akasia** [comment]
lolz

**Comment by ACrazyD** [comment]
Ill leave this ticket open for now, I will state that for more direct help feel free to join the discord :) (I saw you had an issue with it, try to reinstall from the more recent versions on the site)

**Comment by akasia** [comment]
![2024-04-21_21 22 15](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/7fb3aef6-b3a1-4fc8-89c2-d758d3150d66)
![2024-04-21_21 22 48](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/d91df458-d225-4dd2-a3f3-2e249e021101)
still same no enough water or lacking of water>"<

**Comment by ACrazyD** [comment]
Ok ill test it after i work out what the issue was with the boilers

**Comment by akasia** [comment]
k~

**Comment by ACrazyD** [comment]
So what ima do because its wayyyy to picky for a skyblock system here (I admit, i maybe should have tested this before hand) - Im disabling the pickey waterwheels next update be it a hotpatch or full update - I have also removed biome penalty on the windmills while leaving there airflow requirements alone.

Also as to your steam boiler issue - campfires are disabled by default due to "Create: Low Heated" this is intended - with enough work you can run steam off these heaters but in my tests with 2 2x2x8 boilers you will need need to kick start them - and will get about 3k Remaining SU as long as you are really compact about it.

**Comment by akasia** [comment]
![2024-04-21_21 46 49](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/97710c08-7ed3-42f1-9957-76d9697a7eb5)
![2024-04-21_21 47 00](https://github.com/ACrazyD/SkyMachina-Reborn/assets/14824981/477efff6-20ce-4990-80f5-f2a7ea989e66)

**Comment by akasia** [comment]
> So what ima do because its wayyyy to picky for a skyblock system here (I admit, i maybe should have tested this before hand) - Im disabling the pickey waterwheels next update be it a hotpatch or full update - I have also removed biome penalty on the windmills while leaving there airflow requirements alone.
> 
> Also as to your steam boiler issue - campfires are disabled by default due to "Create: Low Heated" this is intended - with enough work you can run steam off these heaters but in my tests with 2 2x2x8 boilers you will need need to kick start them - and will get about 3k Remaining SU as long as you are really compact about it.

that case steam engines at early stage still can't work lacking flintandsteel with using bassic burnner

**Comment by ACrazyD** [comment]
Oh your right! hmm, ill see if i can make an early version of flint and steel to cover that gap.

**Comment by akasia** [comment]
yup normaly if without flinsteel water wheel still can keep up early stage but
currny water wheel did't work still yet not test wind mill mayb can start up with wind mill just didt look up wind mill recipe

**Comment by ACrazyD** [comment]
yep not a worry - this is part of why its a beta pack - i need people to play it to find the issues i miss XD

**Comment by akasia** [comment]
and i just notic some new block but can't craft it that sail from dream & bla bla need rubber frome create
just wander what that it

**Comment by ACrazyD** [comment]
currently bugged - and pending the greggin of create which is in the works (When i can get to it - solo dev issues)

**Comment by akasia** [comment]
oh

**Comment by akasia** [comment]
agin new bug mayb string recipe  plantfiber with knft recipe knift only 1 time use crafting

zz stuck recipe bronze with super heat

and stuck agian on create press recipe /blazeburnner recipe

**Comment by ACrazyD** [comment]
Im going to close this issue as this this problem is long sense solved.
